// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNQLd50AP1UAfDxeMliTU9djvsykUkR8',
    appId: '1:132843442388:web:c009ccd7cf36af3b216b41',
    messagingSenderId: '132843442388',
    projectId: 'data-storage-339220',
    authDomain: 'data-storage-339220.firebaseapp.com',
    storageBucket: 'data-storage-339220.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUlrsgobgGCeCZ6f2f_JQVEbC9PBzWxAU',
    appId: '1:132843442388:android:201268d51b8b81ef216b41',
    messagingSenderId: '132843442388',
    projectId: 'data-storage-339220',
    storageBucket: 'data-storage-339220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUNsqIFYQ5qttc2RN1w2_USFSBGvqk9PM',
    appId: '1:132843442388:ios:7b04d11409470650216b41',
    messagingSenderId: '132843442388',
    projectId: 'data-storage-339220',
    storageBucket: 'data-storage-339220.appspot.com',
    iosClientId: '132843442388-tlrlu6c292jqv5pcar5bpt0moblv1h02.apps.googleusercontent.com',
    iosBundleId: 'com.musamahmood.app',
  );
}
